CREATE DATABASE IF NOT EXISTS visitor_log_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE visitor_log_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  fullname VARCHAR(150) DEFAULT 'Admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visitors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(200) NOT NULL,
  address VARCHAR(255),
  contact VARCHAR(50),
  school_office VARCHAR(150),
  purpose ENUM('INQUIRY','EXAM','VISIT','OTHERS') DEFAULT 'INQUIRY',
  visit_date DATE NOT NULL,
  visit_time TIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
